# #all channel maps are in SpikeGLX user order.
#
# Parameters:
# ===========
# #all:
#   The probe's full channel map in SpikeGLX user order. #all channel numbers are as
#   seen in SGLX. For example, [0] = LF0;384 in the LongColumn map.
# emg_from_lfp:
#    Channels used to derive a virtual EMG.
# superficial_ctx:
#   Visually identified in the LFP during the first 2h of recovery sleep.
# #white_matter:
#   Center of white matter. According to Paxinos and Watson, this should be ~400um
#   from the pyramidal layer, with lower and upper limits of ~266um and ~533um from
#   the pyramidal layer, respectively.
# hippocampus:
#   Identified on the basis of whole-probe CSD during SWRs from the first 2h of
#   recovery sleep.
# drift_tracking:
#   Hippocampal channels, +/- additional channels above and below to #allow for drift.
#   This is probably unnecessary, even for animals with a lot of drift.

# TODO: Remove stratum_pyrmidale_inversion channels, or clarify that they are from the first2h recovery sleep?
# TODO: Fix notes above.
---
subject: CNPIX2-Segundo
experiments:
  novel_objects_deprivation:
    probes:
      imec0:
        imec_map: LongCol_1shank
        internal_reference: [191]
        initial_spw_sink_peak: [153]
        emg_from_lfp: [0, 382, 381]
        scoring: [159, 295, 381]
        superficial_ctx: [375, 377, 379, 381, 383]
        stratum_pyrimidale_inversion: [175] # Manually ID'd during recovery sleep
  isoflurane:
    probes:
      imec0:
        internal_reference: [191]
        emg_from_lfp: [0, 382, 381]
        superficial_ctx: [375, 377, 379, 381, 383]
        stratum_pyrmidale_inversion: [175] # Manually ID'd
...
---
subject: CNPIX3-Valentino
experiments:
  novel_objects_deprivation:
    probes:
      imec0:
        imec_map: CheckPat_1shank
        internal_reference: [191]
        initial_spw_sink_peak: [153]
        emg_from_lfp: [0, 383, 381]
        scoring: [169, 310, 381]
        superficial_ctx: [374, 377, 378, 381, 382]
  sevo-dex:
    probes:
      imec0:
        internal_reference: [191]
        emg_from_lfp: [0, 383, 381]
        superficial_ctx: [374, 377, 378, 381, 382]
        stratum_pyramidale_inversion: [193] # Manually ID'd
  ketamine-90mg:
    probes:
      imec0:
        internal_reference: [191]
        emg_from_lfp: [0, 383, 381]
        superficial_ctx: [374, 377, 378, 381, 382]
        stratum_pyramidale_inversion: [198] # Manually ID'd
  sevoflurane:
    probes:
      imec0:
        internal_reference: [191]
        emg_from_lfp: [0, 383, 381]
        superficial_ctx: [374, 377, 378, 381, 382]
        stratum_pyrmidale_inversion: [206] #Manually ID'd
  atropine:
    probes:
      imec0:
        internal_reference: [191]
        emg_from_lfp: [0, 383, 381]
        superficial_ctx: [374, 377, 378, 381, 382]
        stratum_pyramidale_inversion: [213] # Manually ID'd
  isoflurane:
    probes:
      imec0:
        internal_reference: [191]
        emg_from_lfp: [0, 383, 381]
        superficial_ctx: [374, 377, 378, 381, 382]
        stratum_pyramidale_inversion: [189] # Manually ID'd
...
---
subject: CNPIX4-Doppio
experiments:
  novel_objects_deprivation: &NOD
    probes:
      imec0:
        imec_map: CheckPat_1shank
        internal_reference: [191]
        emg_from_lfp: [0, 383, 381]
        scoring: [150, 310, 381]
        initial_spw_sink_peak: [149]
        superficial_ctx: [374, 377, 378, 381, 382]
        stratum_pyrimidale_inversion: [166] # Manually ID'd
  isoflurane: *NOD
  sevoflurane: &Sevo
    probes:
      imec0:
        internal_reference: [191]
        emg_from_lfp: [0, 383, 381]
        superficial_ctx: [374, 377, 378, 381, 382]
        stratum_pyrmidale_inversion: [170] # Manually ID'd
  dexmedetomidine: *Sevo
  atropine-10mg:
    probes:
      imec0:
        internal_reference: [191]
        emg_from_lfp: [0, 383, 381]
        superficial_ctx: [374, 377, 378, 381, 382]
        stratum_pyrmidale_inversion: [169] # Manually ID'd
  ketamine-120mg:
    probes:
      imec1:
          internal_reference: [191]
          emg_from_lfp: [0, 383, 381]
          superficial_ctx: [374, 377, 378, 381, 382]
          stratum_pyrimidale_inversion: [97] # Manually ID'd
          stratum_radiatum: [77, 78, 81, 82] # 140 um to 200 um from inversion
          scoring: [81, 194, 382]
...
---
subject: CNPIX5-Alessandro
experiments:
  novel_objects_deprivation:
    probes:
      imec0:
        imec_map: LongCol_1shank
        internal_reference: [191]
        emg_from_lfp: [0, 382, 381]
        scoring: [149, 239, 381]
        initial_spw_sink_peak: [151]
        superficial_ctx: [375, 377, 379, 381, 383]
  dexmedetomidine-eStim:
    probes:
      imec0:
        internal_reference: [191]
        emg_from_lfp: [0, 358, 383]
        superficial_ctx: [375, 377, 379, 381, 383]
        stratum_pyramidale_inversion: [175] # Manually ID'd
        stratum_radiatum: [155, 157, 159, 161] # 140um to 200um from SPI.
        scoring: [157, 261, 375]
...
---
subject: CNPIX6-Eugene
experiments:
  novel_objects_deprivation:
    probes:
      imec0:
        imec_map: LongCol_1shank
        internal_reference: [191]
        emg_from_lfp: [0, 382, 381]
        scoring: [187, 309, 381]
        initial_spw_sink_peak: [189]
        superficial_ctx: [375, 377, 379, 381, 383]
...
---
subject: CNPIX7-Giuseppe
experiments:
  novel_objects_deprivation:
    probes:
      imec0: # Frontal
        internal_reference: [191]
        emg_from_lfp: [10, 382, 289]
        scoring: [274, 320, 137, 233]
      imec1: # Posterior
        internal_reference: [191]
        emg_from_lfp: [0, 382, 301]
        scoring: [159, 263, 309]
...
---
subject: CNPIX8-Allan
experiments:
  novel_objects_deprivation:
    probes:
      imec1:
        imec_map: LongCol_Allan
        internal_reference: [191]
        emg_from_lfp: [82, 75, 70]
        scoring: [219, 319, 12]
        initial_spw_sink_peak: [219]
        superficial_ctx: [72, 74, 76, 78, 80]
  dexmedetomidine:
    probes:
      imec0:
        internal_reference: [191]
        emg_from_lfp: [82, 75, 70]
        superficial_ctx: [72, 74, 76, 78, 80]
        stratum_pyramidale_inversion: [207] # Manually ID'd
        stratum_radiatum: [187, 189, 191, 193]
  atropine: &Atropine
    probes:
      imec0:
        internal_reference: [191]
        emg_from_lfp: [82, 75, 70]
        superficial_ctx: [72, 74, 76, 78, 80]
        stratum_pyramidale_inversion: [207] # Manually ID'd
        stratum_radiatum: [187, 189, 191, 193]
  ketamine: *Atropine
...
---
subject: CNPIX9-Luigi
experiments:
  novel_objects_deprivation:
    probes:
      imec0:
        imec_map: LongCol_1shank
        internal_reference: [191]
        emg_from_lfp: [0, 382, 345]
        superficial_ctx: [337, 339, 341, 343, 345]
        stratum_pyramidale_inversion: [137] # Manually ID'd
        stratum_radiatum: [117, 119, 121, 123]
        initial_spw_sink_peak: [121]
        scoring: [119, 263, 337]
  dexmedetomidine:
    probes:
      imec0:
        internal_reference: [191]
        emg_from_lfp: [0, 382, 345]
        superficial_ctx: [297, 299, 301, 303, 305]
        stratum_pyramidale_inversion: [93] # Manually ID'd
        stratum_radiatum: [73, 75, 77, 79]
        scoring: [73, 205, 301]
...
---
subject: CNPIX10-Charles
experiments:
  novel_objects_deprivation:
    probes:
      imec1:
        imec_map: LongCol_1shank
        internal_reference: [191]
        emg_from_lfp: [0, 382, 371]
        superficial_ctx: [375, 377, 379, 381, 383]
        stratum_pyramidale_inversion: [163] # Manually ID'd
        stratum_radiatum: [143, 145, 147, 149]
        initial_spw_sink_peak: [145]
        scoring: [143, 271, 383]
  dexmedetomidine:
    probes:
      imec1:
        internal_reference: [191]
        emg_from_lfp: [0, 382, 383]
        superficial_ctx: [375, 377, 379, 381, 383]
        stratum_pyramidale_inversion: [125] # Manually ID'd
        stratum_radiatum: [105, 107, 109, 111]
        scoring: [105, 247, 303]
...
---
subject: CNPIX11-Adrian
experiments:
  conveyor_over_water:
    probes:
      imec1:
        imec_map: LongCol_1shank
        internal_reference: [191]
        emg_from_lfp: [0, 382, 321]
        superficial_ctx: [313, 315, 317, 319, 321] # Actually deep CTX
        stratum_pyramidale_inversion: [207] # Manually ID'd
        stratum_radiatum: [187, 189, 191, 193]
        initial_spw_sink_peak: [193]
        scoring: [189, 321]
  novel_objects_deprivation:
    probes:
      imec1:
        imec_map: LongCol_1shank
        internal_reference: [191]
        emg_from_lfp: [0, 382, 321]
        superficial_ctx: [313, 315, 317, 319, 321] # Actually deep CTX
        stratum_pyramidale_inversion: [205] # Manually ID'd
        stratum_radiatum: [185, 187, 189, 191]
        initial_spw_sink_peak: [193]
        scoring: [189, 321]
...
---
subject: CNPIX12-Santiago
experiments:
  novel_objects_deprivation:
    probes:
      imec1:
        imec_map: LongCol_1shank
        internal_reference: [191]
        emg_from_lfp: [0, 382, 363]
        superficial_ctx: [357, 359, 361, 363, 365]
        stratum_pyrmidale_inversion: [145]
        stratum_radiatum: [125, 127, 129, 131]
        initial_spw_sink_peak: [125]
        scoring: [125, 231, 365]
  conveyor_over_water:
    probes:
      imec1:
        imec_map: LongCol_1shank
        internal_reference: [191]
        emg_from_lfp: [0, 382, 363]
        superficial_ctx: [357, 359, 361, 363, 365]
        stratum_pyrmidale_inversion: [143]
        stratum_radiatum: [123, 125, 127, 129]
        initial_spw_sink_peak: [125]
        scoring: [125, 241, 365]
...
---
subject: CNPIX13-Al
experiments:
  novel_objects_deprivation:
    probes:
      imec0:
        imec_map: LongCol_1shank
        internal_reference: [191]
        emg_from_lfp: [74, 348, 349]
        scoring: [355, 249, 141, 376]
...
---
subject: ANPIX1-Sputnik
experiments:
  recovery_sleep:
    probes:
      imec0:
        imec_map: Default_1shank
        internal_reference: [191]
      imec1:
        imec_map: Default_1shank
        internal_reference: [191]
        bad: [229, 311, 372]
        suspicious: [23, 47, 71, 95, 119, 143, 167, 215, 239, 263, 287, 383] # Looks like a bad ADC - every 24th channel.
      imec2:
        imec_map: Default_1shank
        internal_reference: [191]
      imec3:
        imec_map: Default_1shank
        internal_reference: [191]
      imec4:
        imec_map: Default_1shank
        internal_reference: [191]
...
---
subject: ANPIX27-Julius
experiments:
  discoflow:
    probes:
      imec0:
        imec_map: Default_1shank
        internal_reference: [191]
      imec1:
        imec_map: Default_1shank
        internal_reference: [191]
        bad: [229, 311, 372]
      imec2:
        imec_map: Default_1shank
        internal_reference: [191]
      imec3:
        imec_map: Default_1shank
        internal_reference: [191]
      imec4:
        imec_map: Default_1shank
        internal_reference: [191]
      imec5:
        imec_map: Default_1shank
        internal_reference: [191]
...
---
subject: ANPIX28-Francis
experiments:
  discoflow:
    probes:
      imec0:
        imec_map: Default_1shank
        internal_reference: [191]
      imec1:
        imec_map: Default_1shank
        internal_reference: [191]
      imec2:
        imec_map: Default_1shank
        internal_reference: [191]
      imec3:
        imec_map: Default_1shank
        internal_reference: [191]
      imec4:
        imec_map: Default_1shank
        internal_reference: [191]
  discoflow-day1:
    probes:
      imec0:
        imec_map: Default_1shank
        internal_reference: [191]
      imec1:
        imec_map: Default_1shank
        internal_reference: [191]
      imec4:
        imec_map: Default_1shank
        internal_reference: [191]
...
---
subject: ANPIX28-Madoc
experiments:
  discoflow-day1: &ANPIX29-Madoc
    probes:
      imec0:
        imec_map: Default_1shank
        internal_reference: [191]
      imec1:
        imec_map: Default_1shank
        internal_reference: [191]
      imec2:
        imec_map: Default_1shank
        internal_reference: [191]
      imec3:
        imec_map: Default_1shank
        internal_reference: [191]
      imec4:
        imec_map: Default_1shank
        internal_reference: [191]
      imec5:
        imec_map: Default_1shank
        internal_reference: [191]
  discoflow-day2: *ANPIX29-Madoc
...
---
subject: ACR2-Fiona
experiments:
  ACR-Test: &ACR2-Fiona
    probes:
      imec0:
        imec_map: Default_1shank
        internal_reference: [191]
      imec1:
        imec_map: Default_1shank
        internal_reference: [191]
      imec2:
        imec_map: Default_1shank
        internal_reference: [191]
      imec3:
        imec_map: Default_1shank
        internal_reference: [191]
      imec4:
        imec_map: Default_1shank
        internal_reference: [191]
  discoflow-day1: *ACR2-Fiona
...
---
subject: ANPIX30-Krapotkin
experiments:
  discoflow-day1: &ANPIX30-Krapotkin
    probes:
      imec0:
        imec_map: Default_1shank
        internal_reference: [191]
      imec1:
        imec_map: Default_1shank
        internal_reference: [191]
      imec2:
        imec_map: Default_1shank
        internal_reference: [191]
      imec3:
        imec_map: Default_1shank
        internal_reference: [191]
      imec4:
        imec_map: Default_1shank
        internal_reference: [191]
      imec5:
        imec_map: Default_1shank
        internal_reference: [191]
...