---
analysis_type: preprocessing
analysis_params:
  prepro_df:
    catgt_path: "/Volumes/scratch/neuropixels/bin/CatGT2.4-linux/runit.sh"
    catgt_params:  &catgt_params_base
      # gbldmx: True  # Replaced by -tshift & -gblcar in v2.2
      gblcar: True
      no_tshift: False
      gfix: '0.40,0.10,0.02'
      ap: True
      lf: False
...
---
analysis_type: sorting
analysis_params:
  # Kilosort 2.5
  ks2_5_base: &ks2_5_base
    ks_path: "/Volumes/scratch/neuropixels/matlab/external/Kilosort-tb-v2.5"
    detect_threshold: 6
    projection_threshold: [10, 4]
    preclust_threshold: 8
    car: True
    minFR: 0.1
    minfr_goodchannels: 0.1
    nblocks: 5
    do_correction: True
    sig: 20
    lam: 10
    freq_min: 150
    sigmaMask: 30
    nPCs: 3
    ntbuff: 64
    nfilt_factor: 4
    NT: null
    keep_good_only: False
    n_jobs_bin: 50
  ks2_5_catgt_df:
    - kilosort2_5 # Gets returned from params.get_analysis_params as 'sorter'
    - &ks2_5_catgt_df
      <<: *ks2_5_base
      car: False
  ks2_5_catgt_Th=12-10_lam=50_8s-batches:
    - kilosort2_5
    -
      <<: *ks2_5_catgt_df
      projection_threshold: [12, 10]
      lam: 50
      NT: 262272
...
---
analysis_type: ks_postprocessing
analysis_params:
  postpro_2:
    # Allan Institute's ecephys_spike_sorting package: [<module_name>: <module_params_dict>]
    - kilosort_postprocessing: {}
    - noise_templates:
        noise_template_use_rf: False
        # Check template spread
        min_spread_threshold: 2
        mid_spread_threshold: 16
        max_spread_threshold: 25
        # Don't check abnormal shape
        min_wavelet_peak_height: 0.0
        min_wavelet_peak_loc: 0
        max_wavelet_peak_loc: 50
        # Extremely lenient on temporal peak location
        min_temporal_peak_location: 2
        max_temporal_peak_location: 50
        # No spatial peak spread testing
        peak_locs_std_thresh: 20
  #         - mean_waveforms: {}  # Don't run
  #         - quality_metrics: {}  # Don't run
  metrics_all_isi:
    # Allan Institute's ecephys_spike_sorting package: [<module_name>: <module_params_dict>]
    - quality_metrics:
        qm_isi_thresh: [0.0020, 0.0015, 0.001]  # Refractory period threshold in sec (to assess contamination). Allen default is 2.0msec for cortex and 1.0msec for thalamus
        tbin_sec: 0.0005  # Refractory period threshold in sec (to assess contamination). Allen default is 2.0msec for cortex and 1.0msec for thalamus
...