# Depths of structures. Corresponding to depths in Phy.
# WATCH OUT: 0 is tip of probe, not necessarily the deepest channel
---
subject: my_subject
probes:
  imec0:  &imec0
    region_1: [0, 1000]
    region_2: [1000, 7660]
experiments:
  my_experiment:
    probes:
      imec0:
        <<: *imec0
        region_2: [1050, 7660]
...
---
subject: CNPIX2-Segundo
experiments:
  novel_objects_deprivation:
    probes:
      imec0: # parietal
        # Cortex
        cortex_inner: [6220, 7580]  # Medial parietal associative cortex. Accounts for 200um error
        cortex_base: [6020, 7580]  # Medial parietal associative cortex. 200um error from these values
        MPPtA_base: [6020, 7580]  # Medial parietal associative cortex. from tip: 302:380. 200um error from these values
        # Hippocampus
        hippocampus_inner: [4540, 5800]  # Accounts for 200um error
        hippocampus_base: [4340, 6000]  # 200um error from these values. from tip: 218:301
        # thal
        thalamus_inner: [1220, 4120]  # Accounts for 200um error
        thalamus_base: [1020, 4320]  # 200um error from these values
        LPMR_base: [3560, 4320]  # Lateral Posterior MedioRostral thal nucleux. LPMR (from tip) = 179:217, 200um error from these values
        Po_base: [2460, 3540]  # Posterior Thal. nucleus. Po (from tip) = 124: 178, 200um error from these values
        VPM_base: [1020, 2440]  # Ventral posteromedial nucleus. VPM (from tip) = 52:123, 200um error from these values
        # hypo thalamus
        hypothalamus_inner: [0, 800]  # Accounts for 200um error.
        hypothalamus_base: [0, 1000]  # 200um error from these values.
        ZI_base: [0, 1000]  # Zona Incerta. ZI (from tip) = 1: 51. 200um error from these values
        white_matter: [5880, 6040] # Added by Graham for SPWRs
        hippocampus: [4080, 5880] # Added by Graham for SPWRs
...
---
subject: CNPIX3-Valentino
experiments:
  novel_objects_deprivation:
    probes:
      imec0:
        white_matter: [6100, 6260] # Added by Graham for SPWRs
        hippocampus: [3800, 6100] # Added by Graham for SPWRs
...
---
subject: CNPIX4-Doppio
experiments:
  novel_objects_deprivation:
    probes:
      imec0: # Parietal
        # Cortex
        cortex_inner: [6160, 7460]  # Medial parietal associative cortex. Accounts for 200um error
        cortex_base: [5960, 7460]  # Medial parietal associative cortex. 200um error from these values
        MPPtA_base: [5960, 7460]  # Medial parietal associative cortex. 200um error from these values
        # Hippocampus
        hippocampus_inner: [4200, 5740]  # Accounts for 200um error
        hippocampus_base: [4000, 5940]  # 200um error from these values
        # thal
        thalamus_inner: [780, 3780]  # Accounts for 200um error
        thalamus_base: [580, 3980]  # 200um error from these values
        LPMR_base: [3060, 3960]  # Lateral Posterior MedioRostral thal nucleux. LPMR (from tip) = 154:199-200, LPMR (from surf) = 210:163. 200um error from these values
        Po_base: [1620, 3040]  # Posterior Thal. nucleus. Po (from tip) = 82: 153, Po (from surf) = 162: 91. 200um error from these values
        VPM_base: [580, 1600]  # Ventral posteromedial nucleus. VPM (from tip) = 30:80-81, VPM (from surf) = 90: 39, 200um error from these values
        # hypo thalamus
        hypothalamus_inner: [0, 360]  # Accounts for 200um error.
        hypothalamus_base: [0, 560]  # 200um error from these values.
        ZI_base: [0, 560]  # Zona Incerta. ZI = 1:29 from tip. 200um error from these values.
        white_matter: [5920, 6080] # Added by Graham for SPWs
        hippocampus: [3700, 5900] # Added by Graham for SPWs
      imec1: # Frontal
        # Neocortex
        cortex_inner: [1820.0, 6540.0]
        cortex_base: [1620.0, 6540.0]
        M2_base: [4780.0, 6540.0] # Secondary motor Cx = 1754 um, 88 channels , M2(from tip) = 240:328, 200um error from these values,,
        A32D_base: [3220.0, 4760.0] # Cingulate Cx = 1540 um, 77 channels , A32D (from tip) = 162:239, 200um error from these values,,
        A32V_base: [1660.0, 3200.0] # Cingulate Cx = 1540 um, 77 channels , A32V (from tip) = 84:161, 200um error from these values,
        # Olfactory cortex
        olfactory_cortex_base: [0.0, 1640.0]
        DP_base: [1040.0, 1640.0]  # Dorsal peduncular Cx 591 um 30 channels DP (from tip) = 53:83. 200um error from these values
        TT_base: [0, 1020.0]  # Tenia tecta 1040 um 52 Channels ,TT (from tip) = 1:52, 200um error from these values.
...
---
subject: CNPIX5-Alessandro
experiments:
  novel_objects_deprivation:
    probes:
      imec0:
        white_matter: [5920, 6080] # Added by Graham for SPWs
        hippocampus: [3700, 5900] # Added by Graham for SPWs
...
---
subject: CNPIX6-Eugene
experiments:
  novel_objects_deprivation:
    probes:
      imec0: # TODO # Parietal
        hypothalamus_base: [0, 980]
        thalamus_base: [980, 3980]
        hippocampus_base: [3980, 6260]
        cortex_base: [6260, 7660]
        white_matter: [6220, 6380] # Added by Graham for SPWs
        hippocampus: [4400, 6200] # Added by Graham for SPWs
      imec1: # TODO  # Frontal
        entorhinal_base: [0, 1780]
        subiculum_base: [1780, 4980]
        cortex_base: [4980, 7660]
...
---
subject: CNPIX7-Giuseppe
experiments:
  novel_objects_deprivation:
    probes:
      imec0: # Frontal
        # Cortex
        cortex_inner: [1920, 6570.0]  # Neo Cortex 4850 um, 242 channels, 200um errror from these values
        cortex_base: [1720, 6570.0]  # Neo Cortex 4850 um, 242 channels, 200um errror from these values
        neocortex_inner: [1920, 6570.0]  # Neo Cortex 4850 um, 242 channels, 200um errror from these values
        neocortex_base: [1720, 6570.0]  # Neo Cortex 4850 um, 242 channels, 200um errror from these values
        # What is this?
        DTr_base: [880.0, 1700.0] # Dorsal transition zone 840 um, 42 channels, Dtr (from tip) = 45:86, 200um error from these values
        # Olfactory
        AO_base: [0.0, 860.0] # Anterior Olfactory area 897 um, 44 Channels, AO (from tip) = 1:44, AO (from surf) = 1:X, 200um error from these values
        # NB: Different frontal probe implantation
      imec1: # Parietal # TODO
        hypothalamus_base: [0, 780]
        thalamus_base: [780, 3880]
        hippocampus_base: [3880, 5980]
        cortex_base: [5980, 7660]
        # NB Different parietal probe implantation
...
---
subject: CNPIX8-Allan
experiments:
  novel_objects_deprivation:
    probes:
      imec0: # Frontal  # TODO (looks correct from cluster distribution)
        neocortex_base: [2500, 7480]
        cortex_base: [2500, 7480]
        olfactory_cortex_base: [0, 2500]
      imec1: # parietal
        # Cortex
        cortex_inner: [7060, 8480]  # Medial parietal associative cortex. Accounts for 200um error
        cortex_base: [6860, 8480]  # Medial parietal associative cortex. 200um error from these values
        cortex_outer: [6660, 8480]  # Medial parietal associative cortex. 200um error from these values
        MPPtA_base: [6860, 8480]  # Medial parietal associative cortex. From tip: 303:386 +820um. 200um error from these values
        # Hippocampus
        hippocampus_inner: [5040, 6640]  # Accounts for 200um error
        hippocampus_base: [4840, 6840]  # From tip: 202:302 +820um. 200um error from these values
        # thal
        thalamus_inner: [1840, 4620]  # Accounts for 200um error
        thalamus_base: [1640, 4820]  # 200um error from these values
        LPMR_base: [4100, 4820]  # Lateral Posterior MedioRostral thal nucleux. LPMR (from tip) = 165:201 + 820um. 200um error from these values
        Po_base: [2280, 4080]  # Posterior Thal. nucleus. Po (from tip) = 74:164 +820um. 200um error from these values
        VPM_base: [1640, 2260]  # Ventral posteromedial nucleus. VPM (from tip) = 42:73 +820um, 200um error from these values
        # hypo thalamus
        hypothalamus_inner: [820, 1420]  # Accounts for 200um error.
        hypothalamus_base: [820, 1620]  # 200um error from these values.
        ZI_base: [820, 1620]  # Zona Incerta. ZI (from tip) = 1: 41, +820um
        white_matter: [6620, 6780] # Added by Graham for SPWs
        hippocampus: [4300, 6600] # Added by Graham for SPWs
...
---
subject: CNPIX9-Luigi
experiments:
  novel_objects_deprivation:
    probes:
      imec0: # Parietal
        # Cortex
        cortex_base: [5180.0, 6980.0]  # 260:350. 200um error from these values
        # Hippocampus
        hippocampus_base: [3020.0, 5140.0]  # 152:258 from . 200um error from these values.
        # thal
        thalamus_base: [0.0, 3000.0]  # 1:151 from tip. 200um error from these values.
        white_matter: [5620, 5780] # Added by Graham for SPWs
        hippocampus: [3500, 5600] # Added by Graham for SPWs
...
---
subject: CNPIX10-Charles
experiments:
  novel_objects_deprivation:
    probes:
      imec0: # Frontal  # TODO
        cortex_base: [3500, 7660]  # TODO
        neocortex_base: [3500, 7660]  # TODO
      imec1: # Parietal
        # Cortex
        cortex_inner: [6280, 7660]  # Medial parietal associative cortex. Accounts for 200um error
        cortex_base: [6080, 7660]  # Medial parietal associative cortex. 200um error from these values
        MPPtA_base: [6080, 7660]  # Medial parietal associative cortex. from tip: 305:388. 200um error from these values
        # Hippocampus
        hippocampus_inner: [4280, 5860]  # Accounts for 200um error
        hippocampus_base: [4080, 6060]  # 200um error from these values. from tip: 205:304
        # thal
        thalamus_inner: [1160, 3860]  # Accounts for 200um error
        thalamus_base: [960, 4060]  # 200um error from these values
        LPMR_base: [3300, 4060]  # Lateral Posterior MedioRostral thal nucleux. LPMR (from tip) = 166:204, 200um error from these values
        Po_base: [2220, 3280]  # Posterior Thal. nucleus. Po (from tip) = 112: 165, 200um error from these values
        VPM_base: [960, 2200]  # Ventral posteromedial nucleus. VPM (from tip) = 49:111, 200um error from these values
        # hypo thalamus
        hypothalamus_inner: [0, 740]  # Accounts for 200um error.
        hypothalamus_base: [0, 940]  # 200um error from these values.
        ZI_base: [0, 940]  # Zona Incerta. ZI (from tip) = 1: 48. 200um error from these values
        white_matter: [5820, 5980] # Added by Graham for SPWs
        hippocampus: [3950, 5800] # Added by Graham for SPWs
...
---
subject: CNPIX11-Adrian
experiments:
  novel_objects_deprivation:
    probes:
      imec0: # Frontal # TODO detailed histology (this was quick reconstruction)
        # Neocortex
        cortex_base: [2720.0, 6780.0] # Neocortex(from tip) = 137:340, 200um error from these values,
        neocortex_base: [2720.0, 6780.0] # Neocortex(from tip) = 137:340, 200um error from these values,
        # Olfactory cortex
        olfactory_cortex_base: [2720.0, 6780.0] # Olfactory area(from tip) = 1:136, 200um error from these values,
      imec1: # Parietal  # TODO detailed histology (this was quick reconstruction)
        # Cortex
        cortex_base: [6100.0, 7660]  # 306:384. 200um error from these values
        # Hippocampus
        hippocampus_base: [4160, 6080]  #  from tip: 209:305. 200um error from these values.
        # thal
        thalamus_base: [1000, 4140]  # 51:208 from tip. 200um error from these values.
        # hypo thalamus
        hypothalamus_base: [0, 980]  # 200um error from these values.
        ZI_base: [0, 980]  # Zona Incerta. ZI (from tip) = 1: 50. 200um error from these values
        white_matter: [6320, 6480] # Added by Graham for SPWs
        hippocampus: [4100, 6300] # Added by Graham for SPWs
  conveyor_over_water:
    probes:
      imec1:
        white_matter: [6320, 6480] # Added by Graham for SPWs
        hippocampus: [4100, 6300] # Added by Graham for SPWs
...
---
subject: CNPIX12-Santiago
experiments:
  novel_objects_deprivation:
    probes:
      imec0: # TODO
        cortex_base: [2500, 7660]  # TODO
      imec1: # TODO
        # Cortex
        cortex_base: [6100.0, 7660]
        # Hippocampus
        hippocampus_base: [4160, 6080]
        # thal
        thalamus_base: [1000, 4140]
        # hypo thalamus
        hypothalamus_base: [0, 980]
        ZI_base: [0, 980]
        hippocampus: [3440, 5700] # Added by Graham for SPWs
        white_matter: [5700, 5900] # Added by Graham for SPWs
  conveyor_over_water:
    probes:
      imec1:
        hippocampus: [3440, 5700] # Added by Graham for SPWs
        white_matter: [5700, 5900] # Added by Graham for SPWs
...