---
project: my_project
project_directory: /Volumes/scratch/neuropixels/data/my_project
...
---
project: catgt  # "catgt" project holds the default location for catGT processed data
project_directory: /Volumes/scratch/neuropixels/data/catgt
...
---
project: SPWRs
project_directory: /Volumes/neuropixel_analysis/Data/SPWRs/
...
---
project: Scoring
project_directory: /Volumes/neuropixel_analysis/Data/Scoring/
...