---
project: my_project
project_directory: /Volumes/neuropixel_analysis/Data/my_project/
...
---
project: catgt  # "catgt" project holds the default location for catGT processed data
project_directory: /nvme/neuropixels/catgt/
...
---
project: acute_sorting
project_directory: /nvme/neuropixels/acute_sorting/
...
---
project: SPWRs
project_directory: /Volumes/neuropixel_analysis/Data/SPWRs/
...
---
project: Scoring
project_directory: /Volumes/neuropixel_analysis/Data/Scoring/
...
---
project: acute
project_directory: /Volumes/neuropixel_analysis/Data/acute/
...