---
subject: my_subject
recording_sessions:
  - id: session_id
    ap: /path/to/raw/ap/{subject_id}/{session_id}/SpikeGLX/
    lf: /path/to/raw/lf/{subject_id}/{session_id}/SpikeGLX/
...
---
subject: CNPIX2-Segundo
recording_sessions:
  - id: 1-21-2020
    ap: /Volumes/neuropixel_archive/Data/chronic/CNPIX2-Segundo/1-21-2020/SpikeGLX/
    lf: /Volumes/neuropixel_archive/Data/chronic/CNPIX2-Segundo/1-21-2020/SpikeGLX/
  - id: 1-24-2020
    ap: /Volumes/neuropixel_archive/Data/chronic/CNPIX2-Segundo/1-24-2020/SpikeGLX/
    lf: /Volumes/neuropixel_archive/Data/chronic/CNPIX2-Segundo/1-24-2020/SpikeGLX/
...
---
subject: CNPIX3-Valentino
recording_sessions:
  - id: 2-19-2020
    ap: /Volumes/neuropixel_archive/Data/chronic/CNPIX3-Valentino/2-19-2020/SpikeGLX/
    lf: /Volumes/neuropixel_archive/Data/chronic/CNPIX3-Valentino/2-19-2020/SpikeGLX/
  - id: 2-20-2020
    ap: /Volumes/neuropixel_archive/Data/chronic/CNPIX3-Valentino/2-20-2020/SpikeGLX/
    lf: /Volumes/neuropixel_archive/Data/chronic/CNPIX3-Valentino/2-20-2020/SpikeGLX/
...
---
subject: CNPIX4-Doppio
recording_sessions:
  - id: 3-17-2020
    ap: /Volumes/neuropixel_archive/Data/chronic/CNPIX4-Doppio/3-17-2020/SpikeGLX/
    lf: /Volumes/neuropixel_archive/Data/chronic/CNPIX4-Doppio/3-17-2020/SpikeGLX/
  - id: 3-18-2020
    ap: /Volumes/neuropixel_archive/Data/chronic/CNPIX4-Doppio/3-18-2020/SpikeGLX/
    lf: /Volumes/neuropixel_archive/Data/chronic/CNPIX4-Doppio/3-18-2020/SpikeGLX/
...
---
subject: CNPIX5-Alessandro
recording_sessions:
  - id: 8-24-2020
    ap: /Volumes/neuropixel_archive/Data/chronic/CNPIX5-Alessandro/8-24-2020/SpikeGLX/
    lf: /Volumes/neuropixel_archive/Data/chronic/CNPIX5-Alessandro/8-24-2020/SpikeGLX/
  - id: 8-25-2020
    ap: /Volumes/neuropixel_archive/Data/chronic/CNPIX5-Alessandro/8-25-2020/SpikeGLX/
    lf: /Volumes/neuropixel_archive/Data/chronic/CNPIX5-Alessandro/8-25-2020/SpikeGLX/
...
---
subject: CNPIX6-Eugene
recording_sessions:
  - id: 9-24-2020
    ap: /Volumes/neuropixel_archive/Data/chronic/CNPIX6-Eugene/9-24-2020/SpikeGLX/
    lf: /Volumes/neuropixel_archive/Data/chronic/CNPIX6-Eugene/9-24-2020/SpikeGLX/
...
---
subject: CNPIX7-Giuseppe
recording_sessions:
  - id: 12-12-2020
    ap: /Volumes/neuropixel_archive/Data/chronic/CNPIX7-Giuseppe/12-12-2020/SpikeGLX/
    lf: /Volumes/neuropixel_archive/Data/chronic/CNPIX7-Giuseppe/12-12-2020/SpikeGLX/
  - id: 12-13-2020
    ap: /Volumes/neuropixel_archive/Data/chronic/CNPIX7-Giuseppe/12-13-2020/SpikeGLX/
    lf: /Volumes/neuropixel_archive/Data/chronic/CNPIX7-Giuseppe/12-13-2020/SpikeGLX/
...
---
subject: CNPIX8-Allan
recording_sessions:
  - id: 3-1-2021
    ap: /Volumes/neuropixel_archive/Data/chronic/CNPIX8-Allan/3-1-2021/SpikeGLX/
    lf: /Volumes/neuropixel_archive/Data/chronic/CNPIX8-Allan/3-1-2021/SpikeGLX/
...
---
subject: CNPIX9-Luigi
recording_sessions:
  - id: 6-20-2021
    ap: /Volumes/neuropixel_archive/Data/chronic/CNPIX9-Luigi/6-20-2021/SpikeGLX/
    lf: /Volumes/neuropixel_archive/Data/chronic/CNPIX9-Luigi/6-20-2021/SpikeGLX/
  - id: 6-21-2021
    ap: /Volumes/neuropixel_archive/Data/chronic/CNPIX9-Luigi/6-21-2021/SpikeGLX/
    lf: /Volumes/neuropixel_archive/Data/chronic/CNPIX9-Luigi/6-21-2021/SpikeGLX/
...
---
subject: CNPIX10-Charles
recording_sessions:
  - id: 7-10-2021
    ap: /Volumes/neuropixel_archive/Data/chronic/CNPIX10-Charles/7-10-2021/SpikeGLX/
    lf: /Volumes/neuropixel_archive/Data/chronic/CNPIX10-Charles/7-10-2021/SpikeGLX/
  - id: 7-11-2021
    ap: /Volumes/neuropixel_archive/Data/chronic/CNPIX10-Charles/7-11-2021/SpikeGLX/
    lf: /Volumes/neuropixel_archive/Data/chronic/CNPIX10-Charles/7-11-2021/SpikeGLX/
...
---
subject: CNPIX11-Adrian
recording_sessions:
  - id: 8-27-2021
    ap: /Volumes/neuropixel_archive/Data/chronic/CNPIX11-Adrian/8-27-2021/SpikeGLX/
    lf: /Volumes/neuropixel_archive/Data/chronic/CNPIX11-Adrian/8-27-2021/SpikeGLX/
  - id: 8-28-2021
    ap: /Volumes/neuropixel_archive/Data/chronic/CNPIX11-Adrian/8-28-2021/SpikeGLX/
    lf: /Volumes/neuropixel_archive/Data/chronic/CNPIX11-Adrian/8-28-2021/SpikeGLX/
  - id: 8-30-2021
    ap: /Volumes/neuropixel_archive/Data/chronic/CNPIX11-Adrian/8-30-2021/SpikeGLX/
    lf: /Volumes/neuropixel_archive/Data/chronic/CNPIX11-Adrian/8-30-2021/SpikeGLX/
  - id: 8-31-2021
    ap: /Volumes/neuropixel_archive/Data/chronic/CNPIX11-Adrian/8-31-2021/SpikeGLX/
    lf: /Volumes/neuropixel_archive/Data/chronic/CNPIX11-Adrian/8-31-2021/SpikeGLX/
...
---
subject: CNPIX12-Santiago
recording_sessions:
  - id: 10-31-2021
    ap: /Volumes/neuropixel_archive/Data/chronic/CNPIX12-Santiago/10-31-2021/SpikeGLX/
    lf: /Volumes/neuropixel_archive/Data/chronic/CNPIX12-Santiago/10-31-2021/SpikeGLX/
  - id: 11-1-2021
    ap: /Volumes/neuropixel_archive/Data/chronic/CNPIX12-Santiago/11-1-2021/SpikeGLX/
    lf: /Volumes/neuropixel_archive/Data/chronic/CNPIX12-Santiago/11-1-2021/SpikeGLX/
  - id: 11-3-2021
    ap: /Volumes/neuropixel_archive/Data/chronic/CNPIX12-Santiago/11-3-2021/SpikeGLX/
    lf: /Volumes/neuropixel_archive/Data/chronic/CNPIX12-Santiago/11-3-2021/SpikeGLX/
  - id: 11-4-2021
    ap: /Volumes/neuropixel_archive/Data/chronic/CNPIX12-Santiago/11-4-2021/SpikeGLX/
    lf: /Volumes/neuropixel_archive/Data/chronic/CNPIX12-Santiago/11-4-2021/SpikeGLX/
...
---
subject: ANPIX1-Sputnik
recording_sessions:
  - id: 10-13-2020
    ap: /Volumes/neuropixel_archive/Data/acute/ANPIX1-Sputnik/10-13-2020/SpikeGLX/
    lf: /Volumes/neuropixel_archive/Data/acute/ANPIX1-Sputnik/10-13-2020/SpikeGLX/
...
---
subject: ANPIX27-Julius
recording_sessions:
  - id: 03-03-2022
    ap: /Volumes/neuropixel_archive/Data/acute/ANPIX27-Julius/03-03-2022/SpikeGLX/
    lf: /Volumes/neuropixel_archive/Data/acute/ANPIX27-Julius/03-03-2022/SpikeGLX/
...

