preprocessing:
  # All preprocessing steps
  # As list because run order is preserved
  # All params are passed to relevant function in spikeinterface
  - 
    step_name: bandpass_filter # si.bandpass_filter
    step_params: 
      freq_min: 300.0
      freq_max: 12000.0
  -
    step_name: phase_shift # si.phase_shift
    step_params: {}
  -
    step_name: common_reference # si.common_reference
    step_params:
      reference: 'local'
      operator: 'median'
  -  # SI recommends correction before whitening
    step_name: drift_correction # preprocess_si_rec._prepro_drift_correction
    step_params:
      # One param dict for each substep
      noise_level_params: {}
      peak_detection_params:
        method: 'locally_exclusive'
        radius_um: 50
        peak_sign: 'neg'
        detect_threshold: 5.0  # Lower than SI preset (8.0) -> messier but more peaks to work with
        exclude_sweep_ms: 0.1
      extract_waveforms_params:
        ms_before: 0.1  # Apparently super short works well and is much faster
        ms_after: 0.3
      peak_localization_method: 'monopolar_triangulation'
      peak_localization_params:
        # Common to "monopolar_triangulation" and "center_of_mass" methods
        radius_um: 75.0
        # Below only for "monopolar_triangulation" method
        max_distance_um: 150.0
        optimizer: 'minimize_with_log_penality'
        enforce_decrease: True
        feature: ptp
      motion_params:
        # General
        bin_duration_s: 60.0
        bin_um: 1.0  # Could be 5um
        margin_um: 0.0  # <0 excludes borders
        rigid: False
        win_shape: "gaussian"
        win_step_um: 1000.0
        win_sigma_um: 1500.0
      motion_method_params:
        method: "decentralized"
        histogram_depth_smooth_um: 5.0
        histogram_time_smooth_s: null
        pairwise_displacement_method: conv
        max_displacement_um: 400.0  # Increased from SI default
        weight_scale: linear
        error_sigma: 0.2
        conv_engine: torch
        # torch_device: null
        batch_size: 1
        corr_threshold: 0.7  # Higher than default (0.0)
        time_horizon_s: null
        convergence_method: lsqr_robust  # Overestimates motion with recommended 'lsmr'
        soft_weights: False
        normalized_xcorr: True
        centered_xcorr: True
        temporal_prior: True
        spatial_prior: False
        force_spatial_median_continuity: False
        reference_displacement: median
        reference_displacement_time_s: 0
        robust_regression_sigma: 2
        weight_with_amplitude: False
      clean_motion_params:
        speed_threshold: 5  # um/sec
        sigma_smooth_s: 60
  -
    step_name: whiten # si.whiten, NB: Need to scale if whitening!
    step_params:
      dtype: 'float32'
  -
    step_name: scale # si.scale, NB: Only if whitening
    step_params:
      gain: 200.0
      offset: 0.0
sorting:
  sorter_name: kilosort2_5
  sorter_path: "/Volumes/scratch/neuropixels/matlab/external/Kilosort-upstream-v2.5"
  sorter_params:  # Passed directly to spikeinterface.run_sorter
    skip_kilosort_preprocessing: True  # DO NOT TOUCH
    scaleproc: 200  # DO NOT TOUCH: MUST be equal to post-whitening scaling during postpro
    nblocks: 0  # DO NOT TOUCH: Effectively skip running kilosort's datashift2.m
    do_correction: False  # DO NOT TOUCH: Effectively skip running kilosort's datashift2.m . Ignord if nblocks=0
    car: True # Ignored
    detect_threshold: 6
    projection_threshold: [10, 4]
    preclust_threshold: 8
    minFR: 0.1
    minfr_goodchannels: 0.1
    sig: 20
    freq_min: 150
    sigmaMask: 30
    nPCs: 3
    ntbuff: 64
    nfilt_factor: 4
    NT: null
    keep_good_only: False