---
subject: CNPIX2-Segundo
experiments:
  novel_objects_deprivation:
    recording_session_ids:
      - 1-21-2020
    aliases:
      light_period_circadian_match:
        start_file: 1-21-2020_g0_t8
        end_file: 1-21-2020_g0_t13
      sleep_deprivation:
        start_file: 1-21-2020_g0_t20
        end_file: 1-21-2020_g0_t22
      recovery_sleep:
        start_file: 1-21-2020_g0_t23
        end_file: 1-21-2020_g0_t25
      light_period:
        start_file: 1-21-2020_g0_t20
        end_file: 1-21-2020_g0_t25
      full_48h:
        start_file: 1-21-2020_g0_t8
        end_file: 1-21-2020_g0_t31
...
---
subject: CNPIX3-Valentino
experiments:
  novel_objects_deprivation:
    recording_session_ids:
      - 2-19-2020
      - 2-20-2020
    aliases:
      light_period_circadian_match:
        start_file: 2-19-2020_g1_t0
        end_file: 2-19-2020_g1_t5
      sleep_deprivation:
        start_file: 2-20-2020_g0_t0
        end_file: 2-20-2020_g0_t2
      recovery_sleep:
        start_file: 2-20-2020_g0_t3
        end_file: 2-20-2020_g0_t5
      light_period:
        start_file: 2-20-2020_g0_t0
        end_file: 2-20-2020_g0_t5
      full_48h:
        start_file: 2-19-2020_g1_t0
        end_file: 2-20-2020_g0_t11
...
---
subject: CNPIX4-Doppio
experiments:
  novel_objects_deprivation:
    recording_session_ids:
      - 3-17-2020
      - 3-18-2020
    aliases:
      light_period_circadian_match:
        start_file: 3-17-2020_g0_t0
        end_file: 3-17-2020_g0_t5
      sleep_deprivation:
        start_file: 3-18-2020_g0_t0
        end_file: 3-18-2020_g0_t2
      recovery_sleep:
        start_file: 3-18-2020_g0_t3
        end_file: 3-18-2020_g0_t5
      light_period:
        start_file: 3-18-2020_g0_t0
        end_file: 3-18-2020_g0_t5
      full_48h:
        start_file: 3-17-2020_g0_t0
        end_file: 3-18-2020_g0_t9
...
---
subject: CNPIX5-Alessandro
experiments:
  novel_objects_deprivation:
    recording_session_ids:
      - 8-24-2020
      - 8-25-2020
    aliases:
      light_period_circadian_match:
        start_file: 8-24-2020_g0_t0
        end_file: 8-24-2020_g0_t11
      sleep_deprivation:
        start_file: 8-25-2020_SD_g0_t0
        end_file: 8-25-2020_g0_t1
      recovery_sleep:
        start_file: 8-25-2020_g0_t2
        end_file: 8-25-2020_g0_t7
      light_period:
        start_file: 8-25-2020_SD_g0_t0
        end_file: 8-25-2020_g0_t7
      full_48h:
        start_file: 8-24-2020_g0_t0
        end_file: 8-25-2020_g0_t12
...
---
subject: CNPIX6-Eugene
experiments:
  novel_objects_deprivation:
    recording_session_ids:
      - 9-24-2020
    aliases:
      light_period_circadian_match:
        start_file: 9.24.2020_BL_24hs_g0_t0
        end_file: 9.24.2020_BL_24hs5_g0_t0
      sleep_deprivation:
        start_file: 9.24.2020_SD_24hs_g0_t0
        end_file: 9.24.2020_SD_24hs8_g0_t1
      recovery_sleep:
        start_file: 9.24.2020_SR_24hs_g0_t0
        end_file: 9.24.2020_SR_24hs1_g0_t0
      light_period:
        start_file: 9.24.2020_SD_24hs_g0_t0
        end_file: 9.24.2020_SR_24hs1_g0_t0
      full_48h:
        start_file: 9.24.2020_BL_24hs_g0_t0
        end_file: 9.24.2020_SR_24hs5_g0_t2
...
---
subject: CNPIX7-Giuseppe
experiments:
  novel_objects_deprivation:
    recording_session_ids:
      - 12-12-2020
      - 12-13-2020
    aliases:
      light_period_circadian_match:
        start_file: 12-12-2020_BL_24hs_g0_t0
        end_file: 12-12-2020_BL_24hs_g0_t10
      sleep_deprivation:
        start_file: 12.12.2020 SD 6hs_g0_t0
        end_file: 12.13.2020 SD 6hs (restart_2)_g2_t2
      recovery_sleep:
        start_file: 12-13-2020_SR_18hs_g0_t0
        end_file: 12-13-2020_SR_18hs_g0_t5
      light-period:
        start_file: 12.12.2020 SD 6hs_g0_t0
        end_file: 12-13-2020_SR_18hs_g0_t5
      full_48h:
        start_file: 12-12-2020_BL_24hs_g0_t0
        end_file: 12-13-2020_SR_18hs_g0_t6
...
---
subject: CNPIX8-Allan
experiments:
  novel_objects_deprivation:
    recording_session_ids:
      - 3-1-2021
    aliases:
      light_period_circadian_match:
        start_file: 3-1-2021_g0_t0
        end_file: 3-1-2021_C_g0_t8
      sleep_deprivation:
        start_file: 3-2-2021_A_g0_t0
        end_file: 3-2-2021_E_g0_t0
      recovery_sleep:
        start_file: 3-2-2021_F_g0_t0
        end_file: 3-2-2021_G_g0_t0
      light_period:
        start_file: 3-2-2021_A_g0_t0
        end_file: 3-2-2021_G_g0_t0
      full_48h:
        start_file: 3-1-2021_g0_t0
        end_file: 3-2-2021_O_g0_t0
...
---
subject: CNPIX9-Luigi
experiments:
  novel_objects_deprivation:
    recording_session_ids:
      - 6-20-2021
      - 6-21-2021
    aliases:
      light_period_circadian_match:
        start_file: 6-20-2021_g0_t0
        end_file: 6-20-2021_g0_t5
      sleep_deprivation:
        start_file: 6-21-2021_g0_t0
        end_file: 6-21-2021_g0_t2
      recovery_sleep:
        start_file: 6-21-2021_g1_t0
        end_file: 6-21-2021_g1_t2
      light_period:
        start_file: 6-21-2021_g0_t0
        end_file: 6-21-2021_g1_t2
      full_48h:
        start_file: 6-20-2021_g0_t0
        end_file: 6-21-2021_g1_t8
...
---
subject: CNPIX10-Charles
experiments:
  novel_objects_deprivation:
    recording_session_ids:
      - 7-10-2021
      - 7-11-2021
    aliases:
      light_period_circadian_match:
        start_file: 7-10-2021_g0_t0
        end_file: 7-10-2021_g0_t5
      sleep_deprivation:
        start_file: 7-11-2021_g0_t0
        end_file: 7-11-2021_g0_t2
      recovery_sleep:
        start_file: 7-11-2021_g1_t0
        end_file: 7-11-2021_g1_t2
      light-period:
        start_file: 7-11-2021_g0_t0
        end_file: 7-11-2021_g1_t2
      full_48h:
        start_file: 7-10-2021_g0_t0
        end_file: 7-11-2021_g1_t8
...
---
subject: CNPIX11-Adrian
experiments:
  conveyor_over_water:
    recording_session_ids:
      - 8-27-2021
      - 8-28-2021
    aliases:
      light_period_circadian_match:
        start_file: 8-27-2021_g2_t0
        end_file: 8-27-2021_g2_t5
      sleep_deprivation:
        start_file: 8-28-2021_g0_t0
        end_file: 8-28-2021_g0_t2
      recovery_sleep:
        start_file: 8-28-2021_g0_t3
        end_file: 8-28-2021_g0_t5
      light_period:
        start_file: 8-28-2021_g0_t0
        end_file: 8-28-2021_g0_t5
      full_48h:
        start_file: 8-27-2021_g2_t0
        end_file: 8-28-2021_g0_t11
  novel_objects_deprivation:
    recording_session_ids:
      - 8-30-2021
      - 8-31-2021
    aliases:
      light_period_circadian_match:
        start_file: 8-30-2021_g0_t0
        end_file: 8-30-2021_g0_t5
      sleep_deprivation:
        start_file: 8-31-2021_g0_t0
        end_file: 8-31-2021_g0_t2
      recovery_sleep:
        start_file: 8-31-2021_g0_t3
        end_file: 8-31-2021_g0_t5
      light_period:
        start_file: 8-31-2021_g0_t0
        end_file: 8-31-2021_g0_t5
      full_48h:
        start_file: 8-30-2021_g0_t0
        end_file: 8-31-2021_g1_t0
...
---
subject: CNPIX12-Santiago
experiments:
  novel_objects_deprivation:
    recording_session_ids:
      - 10-31-2021
      - 11-1-2021
    aliases:
      light_period_circadian_match:
        start_file: 10-31-2021_g0_t0
        end_file: 10-31-2021_g0_t5
      sleep_deprivation:
        start_file: 11-1-2021_g0_t0
        end_file: 11-1-2021_g0_t2
      recovery_sleep:
        start_file: 11-1-2021_g1_t0
        end_file: 11-1-2021_g1_t2
      light_period:
        start_file: 11-1-2021_g0_t0
        end_file: 11-1-2021_g1_t2
      full_48h:
        start_file: 10-31-2021_g0_t0
        end_file: 11-1-2021_g1_t8
  conveyor_over_water:
    recording_session_ids:
      - 11-3-2021
      - 11-4-2021
    aliases:
      light_period_circadian_match:
        start_file: 11-3-2021_g0_t0
        end_file: 11-3-2021_g0_t5
      sleep_deprivation:
        start_file: 11-4-2021_g0_t0
        end_file: 11-4-2021_g0_t2
      recovery_sleep:
        start_file: 11-4-2021_g0_t3
        end_file: 11-4-2021_g0_t5
      light_period:
        start_file: 11-4-2021_g0_t0
        end_file: 11-4-2021_g0_t5
      full_48h:
        start_file: 11-3-2021_g0_t0
        end_file: 11-4-2021_g0_t11
...